<?php

namespace App\Services\Networking;

use App\Models\Lab;
use Carbon\Carbon;
use Exception;

/**
 * Orchestrates the lifecycle of Containerlab labs.
 *
 * In production, this class would execute shell commands and talk to the
 * Containerlab API/daemon.  When the daemon is unavailable, it falls back
 * to a simulation that inspects the .clab definition and returns realistic
 * but synthetic state.
 */
class LabOrchestrator
{
    public const STATUS_STOPPED = 'stopped';

    public const STATUS_RUNNING = 'running';

    public const STATUS_ERROR = 'error';

    // Simulations shorter than 30s would look unrealistic.
    private const SIMULATION_DELAY_SECONDS = 3;

    /**
     * Parse the clab-definition field into an array.
     */
    public function parseDefinition(string $clabYaml): array
    {
        $def = json_decode(json_encode(simplexml_load_string($clabYaml)), true);
        if ($def !== null && $def !== false) {
            return $def;
        }

        // Fall back to treating the whole definition as a devices list.
        return $this->inferDevicesFromTopology($clabYaml);
    }

    /**
     * Start a lab. If the Containerlab daemon is reachable, deploy. Otherwise,
     * mock the start with fake node status.
     */
    public function start(Lab $lab): Lab
    {
        $devices = $this->parseDevices($lab);

        if ($this->isDaemonAvailable()) {
            // Production path: execute containerlab deploy, parse JSON output
            $nodeStatus = $this->deployRealLab($lab, $devices);
        } else {
            $nodeStatus = $this->mockNodeStatus($devices, self::STATUS_RUNNING);
        }

        $lab->fill([
            'status' => self::STATUS_RUNNING,
            'devices' => $lab->devices ?? $devices,
            'node_status' => $nodeStatus,
            'started_at' => Carbon::now(),
        ])->save();

        return $lab;
    }

    /**
     * Stop a lab.
     */
    public function stop(Lab $lab): Lab
    {
        if ($this->isDaemonAvailable()) {
            $this->execCmd(['containerlab', 'destroy', '-t', $lab->lab_directory.'/topology.clab.yml']);
        }

        $devices = $lab->devices ?: ($lab->clab_definition ? $this->parseDevices($lab) : []);
        $nodeStatus = $this->mockNodeStatusForStopped($devices);

        $lab->fill([
            'status' => self::STATUS_STOPPED,
            'node_status' => $nodeStatus,
            'started_at' => null,
            'stopped_at' => Carbon::now(),
        ])->save();

        return $lab;
    }

    /**
     * Refresh live status (node_status).
     */
    public function refresh(Lab $lab): Lab
    {
        if ($lab->status !== self::STATUS_RUNNING) {
            return $lab;
        }

        if ($this->isDaemonAvailable()) {
            $nodeStatus = $this->pollRealLabStatus($lab);
        } else {
            $devices = $lab->devices ?: ($lab->clab_definition ? $this->parseDevices($lab) : []);
            $uptime = (int) Carbon::now()->diffInMinutes($lab->started_at ?? Carbon::now());
            $nodeStatus = $this->mockNodeUptime($devices, $uptime);
        }

        $lab->node_status = $nodeStatus;
        $lab->save();

        return $lab;
    }

    /**
     * Build a .clab.yml string from a topology design.
     *
     * @param  array<string, mixed>  $devices
     */
    public function constructDefinition(string $name, array $devices): string
    {
        $parts = [];

        $parts[] = '# Auto-generated by Polymind';
        $parts[] = 'name: '.str($name)->slug();
        $parts[] = 'topology:';
        $parts[] = '  nodes:';

        foreach ($devices as $device) {
            $slug = $device['slug'] ?? str($device['name'])->slug();
            $kind = $device['kind'] ?? $device['type'] ?? 'generic';
            $image = $device['image'] ?? $this->defaultImage($kind);
            $parts[] = '    '.$slug.':';
            $parts[] = '      kind: '.$kind;
            $parts[] = '      image: '.$image;
            $parts[] = '      mgmt-ip: 0.0.0.0';

            if (! empty($device['port_count'])) {
                $parts[] = '      ports:';
                for ($i = 1; $i <= (int) $device['port_count']; $i++) {
                    $parts[] = "        - slot: 0/$i";
                    $parts[] = '          type: ethernet-c';
                }
            }
        }

        // topology-level links (collected from every device that declares them)
        $links = [];
        foreach ($devices as $device) {
            foreach (($device['links'] ?? []) as $link) {
                $links[] = "    - endpoints: [\"{$link['from']}\", \"{$link['to']}\"]";
            }
        }
        if ($links !== []) {
            $parts[] = '  links:';
            foreach ($links as $l) {
                $parts[] = $l;
            }
        }

        return implode("\n", $parts);
    }

    /**
     * @return array<int, array{name: string, slug: string, kind: string, image: string}>
     */
    public function parseDevices(Lab $lab): array
    {
        if ($lab->clab_definition) {
            return $this->inferDevicesFromTopology($lab->clab_definition);
        }

        return $lab->devices ?? [];
    }

    // ---------------------------------------------------------------
    // Private helpers
    // ---------------------------------------------------------------

    private function defaultImage(string $kind): string
    {
        $images = [
            'vr-cisco' => 'vrnetlab/vr-cisco-iol:latest',
            'vr-xe' => 'vrnetlab/vr-xe:latest',
            'catalyst' => 'vrnetlab/vr-csr1000v:latest',
            'c8000' => 'vrnetlab/vr-c8000v:latest',
            'linux' => 'alpine:latest',
            'generic' => 'alpine:latest',
        ];

        return $images[$kind] ?? 'alpine:latest';
    }

    /**
     * Infers device parameters by scanning the entire clab_definition text.
     */
    private function inferDevicesFromTopology(string $definition): array
    {
        $devices = [];
        $lines = explode("\n", $definition);

        $currentSlug = null;
        foreach ($lines as $line) {
            if (preg_match('/^    (\w[\w-]*):/', $line, $slugMatch)) {
                $currentSlug = $slugMatch[1];
                $devices[$currentSlug] = ['name' => $currentSlug, 'slug' => $currentSlug, 'kind' => 'generic', 'image' => 'alpine:latest'];
            } elseif ($currentSlug && preg_match('/kind:\s*(.+)/', $line, $kindMatch)) {
                $devices[$currentSlug]['kind'] = trim($kindMatch[1]);
            } elseif ($currentSlug && preg_match('/image:\s*(.+)/', $line, $imageMatch)) {
                $devices[$currentSlug]['image'] = trim($imageMatch[1]);
            }
        }

        return $devices;
    }

    private function mockNodeStatus(array $devices, string $status): array
    {
        return array_map(function ($d) use ($status) {
            return [
                'name' => $d['slug'] ?? $d['name'] ?? 'unknown',
                'status' => $status,
                'uptime' => $status === self::STATUS_RUNNING ? 0 : null,
                'stats' => [
                    'cpu' => 0,
                    'memory' => 0,
                    'disk' => 0,
                ],
            ];
        }, $devices);
    }

    private function mockNodeStatusForStopped(array $devices): array
    {
        return array_map(function ($d) {
            return [
                'name' => $d['slug'] ?? $d['name'] ?? 'unknown',
                'status' => self::STATUS_STOPPED,
                'uptime' => null,
                'stats' => ['cpu' => 0, 'memory' => 0, 'disk' => 0],
            ];
        }, $devices);
    }

    private function mockNodeUptime(array $devices, int $uptimeMinutes): array
    {
        return array_map(function ($d) use ($uptimeMinutes) {
            return [
                'name' => $d['slug'] ?? $d['name'] ?? 'unknown',
                'status' => self::STATUS_RUNNING,
                'uptime' => $uptimeMinutes,
                'stats' => [
                    'cpu' => round(rand(10, 90) + rand(0, 99) / 100, 2),
                    'memory' => round(rand(20, 80) + rand(0, 99) / 100, 2),
                ],
            ];
        }, $devices);
    }

    private function isDaemonAvailable(): bool
    {
        $output = $this->execCmd(['containerlab', 'version', '--short']);

        return $output !== null && $output['code'] === 0;
    }

    private function deployRealLab(Lab $lab, array $devices): array
    {
        $dir = $lab->lab_directory;
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents(
            $dir.'/topology.clab.yml',
            $lab->clab_definition ?? $this->constructDefinition($lab->name, $devices)
        );

        $output = $this->execCmd([
            'containerlab', 'deploy', '-t', $dir.'/topology.clab.yml', '--format', 'json',
        ]);

        if ($output !== null && $output['code'] === 0) {
            return $this->parseContainerlabStatus($output['stdout']);
        }

        throw new Exception('Unable to deploy lab');
    }

    private function pollRealLabStatus(Lab $lab): array
    {
        $output = $this->execCmd([
            'containerlab', 'inspect', '-t', $lab->lab_directory.'/topology.clab.yml',
        ]);

        if ($output !== null && $output['code'] === 0) {
            return $this->parseContainerlabStatus($output['stdout']);
        }

        return $lab->node_status ?? [];
    }

    /**
     * Parse the JSON output of containerlab inspect/deploy.
     * Returns an array of node status compatible with the node_status JSON field.
     */
    private function parseContainerlabStatus(string $stdout): array
    {
        $nodes = json_decode($stdout, true);
        if (! is_array($nodes)) {
            return [];
        }

        return array_map(function ($node) {
            return [
                'name' => $node['Name'],
                'status' => $node['State'] ?? self::STATUS_RUNNING,
                'uptime' => $node['UpTime'] ?? null,
                'stats' => [
                    'cpu' => $node['CPU'] ?? 0,
                    'memory' => $node['Memory'] ?? 0,
                    'disk' => $node['Disk'] ?? 0,
                ],
            ];
        }, $nodes);
    }

    /**
     * Execute a command and return stdout, stderr, and exit code.
     *
     * @param  array<int, string>  $command
     * @return array{stdout: string, stderr: string, code: int}|null
     */
    private function execCmd(array $command): ?array
    {
        $escaped = array_map(function ($piece) {
            return escapeshellarg($piece);
        }, $command);

        $proc = proc_open(
            implode(' ', $escaped),
            [
                0 => ['pipe', 'r'],
                1 => ['pipe', 'w'],
                2 => ['pipe', 'w'],
            ],
            $pipes
        );

        if (! is_resource($proc)) {
            return null;
        }

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);

        fclose($pipes[1]);
        fclose($pipes[2]);
        $code = proc_close($proc);

        return compact('stdout', 'stderr', 'code');
    }
}
